
### 
POST http://localhost:3001/signup HTTP/1.1
content-type: application/json

{
    "username":"Hendry",
    "password":"123123",
    "grade": 2
}

### 
POST http://localhost:3001/signin HTTP/1.1
content-type: application/json

{
    "username":"Hendry",
    "password":"123123"
}

###
POST http://localhost:3001/profile HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123",
    "token": ""
}


###
POST http://localhost:3001/signup/checkUsername HTTP/1.1
Content-Type: application/json

{
    "username": "peter"
}







# ###
# POST http://localhost:3001/poetry/dog HTTP/1.1
# Content-Type: application/json

# {
#     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbmRyeSIsInR5cGUiOjEsImlhdCI6MTU4MDYyNDIyOSwiZXhwIjoxNTgwNjMxNDI5fQ.yrcB_T7VPhSayNwgwYAN0t_8wKRSugR73Fh-422QbqE"
# }


### 获取诗词
POST http://localhost:3001/poetry/getPoetries HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidHlwZSI6MCwiaWF0IjoxNTgwNjMxNzU4LCJleHAiOjE1ODA2Mzg5NTh9.NAzOFrvXCalSsWlErgrf7HpkArqWMAimuojsIYr6Mio",
    "currentPage": 1,
    "pageSize": 2
}

### 修改诗词
POST http://localhost:3001/poetry/modifyPoetry HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidHlwZSI6MCwiaWF0IjoxNTgwNjQxNzM4LCJleHAiOjE1ODA2NDg5Mzh9.VTTQpspbPB5d4JBEGme0hqV_nev1RyW79Anla5Ba7GI",
    "poetry": {
        "_id": "5e36b430cfd97634b46c3707",
        "type": ["抒情123123"]
    }
}

###
POST http://localhost:3001/poetry/deletePoetry HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidHlwZSI6MCwiaWF0IjoxNTgwNjQxNzM4LCJleHAiOjE1ODA2NDg5Mzh9.VTTQpspbPB5d4JBEGme0hqV_nev1RyW79Anla5Ba7GI"
}



###
POST http://localhost:3001/poetry/createPoetry HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidHlwZSI6MCwiaWF0IjoxNTgwNjQxNzM4LCJleHAiOjE1ODA2NDg5Mzh9.VTTQpspbPB5d4JBEGme0hqV_nev1RyW79Anla5Ba7GI",
   "poetry": {
       "type": "laksjdflkj",
        "title":"lkajlsdkfqer",
        "dynasty":"laksdfjlqwer",
        "writer": "lkj11",
        "content": "l1kjads",
        "remark": "123123",
        "translation": "123123",
        "appreciation": "123132",
        "audioUrl":"hello"
    }
}