
### 注册
POST http://localhost:3001/signup HTTP/1.1
content-type: application/json

{
    "username":"Hendry",
    "password":"123123",
    "grade": 2
}

### 登录
POST http://localhost:3001/signin HTTP/1.1
content-type: application/json

{
    "username":"Hendry",
    "password":"123123"
}

### 主页面
POST http://localhost:3001/profile HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123",
    "token": ""
}


### 检查昵称
POST http://localhost:3001/signup/checkUsername HTTP/1.1
Content-Type: application/json

{
    "username": "peter"
}


### 获取诗词
POST http://localhost:3001/poetry/getPoetries HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidHlwZSI6MCwiaWF0IjoxNTgwNjMxNzU4LCJleHAiOjE1ODA2Mzg5NTh9.NAzOFrvXCalSsWlErgrf7HpkArqWMAimuojsIYr6Mio",
    "currentPage": 1,
    "pageSize": 2
}

### 修改诗词
POST http://localhost:3001/poetry/modifyPoetry HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidHlwZSI6MCwiaWF0IjoxNTgwNjQxNzM4LCJleHAiOjE1ODA2NDg5Mzh9.VTTQpspbPB5d4JBEGme0hqV_nev1RyW79Anla5Ba7GI",
    "poetry": {
        "_id": "5e36b430cfd97634b46c3707",
        "type": ["抒情123123"]
    }
}

### 
POST http://localhost:3001/poetry/deletePoetry HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidHlwZSI6MCwiaWF0IjoxNTgwNjQxNzM4LCJleHAiOjE1ODA2NDg5Mzh9.VTTQpspbPB5d4JBEGme0hqV_nev1RyW79Anla5Ba7GI"
}



###
POST http://localhost:3001/poetry/createPoetry HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidHlwZSI6MCwiaWF0IjoxNTgwNjQxNzM4LCJleHAiOjE1ODA2NDg5Mzh9.VTTQpspbPB5d4JBEGme0hqV_nev1RyW79Anla5Ba7GI",
   "poetry": {
       "type": "laksjdflkj",
        "title":"lkajlsdkfqer",
        "dynasty":"laksdfjlqwer",
        "writer": "lkj11",
        "content": "l1kjads",
        "remark": "123123",
        "translation": "123123",
        "appreciation": "123132",
        "audioUrl":"hello"
    }
}


### 作者列表
POST http://localhost:3001/writer/getWriters HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidHlwZSI6MCwiaWF0IjoxNTgwOTc2NDg4LCJleHAiOjE1ODA5ODM2ODh9._x14c0X6WND8hL2_DQHO9FGfqz5keLesVA4ZQudNfpA",
    "currentPage": 0,
    "pageSize": 10
}



### 增加作者
POST http://localhost:3001/writer/createWriter HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidHlwZSI6MCwiaWF0IjoxNTgwOTc2NDg4LCJleHAiOjE1ODA5ODM2ODh9._x14c0X6WND8hL2_DQHO9FGfqz5keLesVA4ZQudNfpA",
    "writer": {
        "name": "peter",
        "simpleIntro": "laksdjflakjdsf",
        "detailIntro": "lkajsdlkfjqwer"
    }
}



### 删除作者
POST http://localhost:3001/writer/deleteWriter HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidHlwZSI6MCwiaWF0IjoxNTgwODg3MDQwLCJleHAiOjE1ODA4OTQyNDB9.KnEF1MhxHO3HKf-PTppZ_7iMnJ5ixe99FEdir5UWD8I",
    "_id": "5e3a76fd22b49d12341c6551"
}



### 修改作者信息
POST http://localhost:3001/writer/modifyWriter HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidHlwZSI6MCwiaWF0IjoxNTgwODg3MDQwLCJleHAiOjE1ODA4OTQyNDB9.KnEF1MhxHO3HKf-PTppZ_7iMnJ5ixe99FEdir5UWD8I",
    "writer": {
        "_id": "5e3a77bc419ecb2554a01d8d",
        "name": "123123123"
    }
}