
### like
POST http://localhost:3001/poetry/like HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldGVyIiwidHlwZSI6MSwiX2lkIjoicGV0ZXIiLCJpYXQiOjE1ODIwOTUxNzAsImV4cCI6MTU4MjEwMjM3MH0.kOEBPRFAzBFTe-21X_bdyRVgMoJhlWr7-kg_feNcMaE",
    "poetry_id": "5b9a0136367d5c96f4cd2952"
}


